// Style records (Design Library V2). Data only: tokens, type, treatment,
// declarative decoration, layout, roles, formats, provenance and status.
// lib/studio/styles.js validates and applies them; docs/library/matrix.json
// says which composition pairs passed QA. A style is offered as ready only
// with status "reusable".
//
// Source values are inputs, never identity: the brand's accent replaces the
// source accent, Arabic faces replace Latin ones, and every visual decision
// made here for Arabic social posts is listed under "designedHere".

import { sourceRef } from './sources.js';

export const STYLES = [
  {
    kind: 'style',
    id: 'quiet-editorial',
    version: 1,
    status: 'reusable',
    family: 'editorial',
    name: 'تحريري هادئ',
    purpose: 'مقالات وقوائم هادئة القراءة: عنوان كبير في أعلى الصفحة، فراغ واسع، ولون تمييز واحد في كل صفحة',
    tone: 'متأنٍّ، واثق، بلا زخرفة',
    distinctFrom: { style: 'classic', how: 'بلا دوائر زخرفية ولا بطاقات مملوءة: بطاقات بإطار رفيع، وأرقام بلون التمييز بلا دوائر، وكتلة المحتوى مائلة إلى الأعلى، وزخرفة واحدة بلون التمييز فقط' },
    tokens: {
      light: { bg: '#FAF7F2', surface: '#FFFFFF', text: '#1C1A17', muted: '#6F6760' },
    },
    defaultMode: 'light',
    type: { titleScale: 1, titleWeight: 'bold', titleLineHeight: 1.35, headingFont: 'cairo', bodyFont: 'tajawal' },
    treatment: { pillRadius: 12, pillFill: 'outline', cardMode: 'outline', cardRadius: 16, badge: 'plain', ruleFill: '@text', ruleRadius: 0, artRadius: 16 },
    layout: { stackAlign: 'upper', margin: 96, maxScale: 1.35 },
    decor: {
      cover: [{ shape: 'rect', at: 'start', x: 'M', y: 'R-44', w: 140, h: 10, fill: '@accent', name: 'علامة التمييز الوحيدة' }],
      content: [{ shape: 'rect', at: 'start', x: 'M', y: 'R-32', w: 'W-2*M', h: 2, fill: '@muted', opacity: 0.45, name: 'خط علوي رفيع' }],
      cta: [{ shape: 'rect', at: 'start', x: 'M', y: 'R-44', w: 140, h: 10, fill: '@accent', name: 'علامة التمييز الوحيدة' }],
    },
    densities: ['comfortable', 'airy'],
    // Roles not claimed, and why (a design decision, not a test result).
    notFor: { comparison: 'المقارنة تحتاج جهتين متمايزتين بوضوح؛ البطاقات بإطار رفيع والخلفية البيضاء تضعفان الفرق بينهما', collage: 'القصاصات المائلة بأشرطتها اللاصقة لغة بصرية مستقلة؛ لا تُدمج مع هذا الأسلوب' },
    roles: ['cover', 'list', 'steps', 'quote', 'statement', 'evidence', 'framework', 'cta'],
    formats: ['portrait', 'square', 'story'],
    rtl: ['المحاذاة من البداية (اليمين)', 'لا تباعد حروف ولا أحرف كبيرة', 'الزخرفة تُقاس من بداية القراءة'],
    provenance: [
      {
        source: sourceRef('opendesign/warm-editorial'),
        extracted: ['الخلفية الورقية #FAF7F2 والنص #1C1A17 والسطح #FFFFFF', 'زوايا بين 8 و24 (البطاقات 16 والأزرار 12)', 'لون تمييز واحد لكل صفحة', 'المحتوى مائل إلى الأعلى لا في الوسط', 'لا تدرجات ولا ظلال إلا للرفع'],
        adapted: ['لون التمييز الطيني استُبدل بلون الهوية', 'الخط الرأسي اللاتيني (serif) استُبدل بـ Cairo لعدم وجود خط عربي مذيّل في المجموعة', 'ارتفاع السطر 1.2/1.6 رُفع إلى 1.35/1.7 للتشكيل والنقاط', 'الرمادي #8A817A غُمّق إلى #6F6760 ليبلغ تباين 4.5'],
        notUsed: ['تباعد الحروف السالب', 'Title Case', 'شبكة 12 عمودًا لصفحات الويب'],
      },
    ],
    designedHere: ['خط علوي رفيع لصفحات المحتوى', 'أرقام القوائم بلون التمييز بلا دوائر', 'شارة بإطار بدل التعبئة'],
    keepCompositionDecor: false,
  },
  {
    kind: 'style',
    id: 'magazine-bold',
    version: 1,
    status: 'reusable',
    family: 'magazine',
    name: 'مجلة جريئة',
    purpose: 'أفكار عملية ونصائح سريعة بإيقاع مجلة: غلاف وخاتمة داكنان، عناوين ثقيلة كبيرة، ورقم شبحي في صفحات المحتوى',
    tone: 'واثق، مباشر، عالي التباين',
    distinctFrom: { style: 'quiet-editorial', how: 'عناوين أثقل وأكبر، غلاف وخاتمة بالأزرق الليلي، زوايا حادة، بطاقات مملوءة بعلامة تمييز قصيرة، رقم شبحي ضخم خلف المحتوى' },
    tokens: {
      light: { bg: '#FFFFFF', surface: '#EEF2F7', text: '#0B1220', muted: '#4A5565' },
      dark: { bg: '#0E2A5C', surface: '#173B74', text: '#FFFFFF', muted: '#C9D4E3' },
    },
    defaultMode: 'light',
    modeByRole: { cover: 'dark', cta: 'dark' },
    type: { titleScale: 1.12, titleWeight: 'black', titleLineHeight: 1.25 },
    treatment: { pillRadius: 0, pillFill: '@accent', cardMode: 'accent-bar', cardRadius: 0, badge: 'rect', ruleFill: '@accent', ruleRadius: 0, rule: { width: 220, height: 14 }, artRadius: 0 },
    layout: { stackAlign: 'center', margin: 88, maxScale: 1.2 },
    decor: {
      cover: [{ shape: 'rect', at: 'start', x: 0, y: 'T', w: 'W/2', h: 24, fill: '@accent', name: 'شريط الغلاف' }],
      content: [{ shape: 'ghost-number', at: 'end', x: 'M-24', y: 'F-300', w: 420, h: 330, fill: '@text', opacity: 0.05, compositions: ['statement', 'quote', 'post'], name: 'رقم الصفحة الشبحي' }],
      cta: [{ shape: 'rect', at: 'start', x: 0, y: 'H-B-24', w: 'W/2', h: 24, fill: '@accent', name: 'شريط الخاتمة' }],
    },
    densities: ['comfortable', 'dense'],
    // Roles not claimed, and why (a design decision, not a test result).
    notFor: { collage: 'القصاصات المائلة بأشرطتها اللاصقة لغة بصرية مستقلة؛ لا تُدمج مع هذا الأسلوب' },
    roles: ['cover', 'list', 'steps', 'statement', 'evidence', 'framework', 'comparison', 'quote', 'cta'],
    formats: ['portrait', 'story'],
    rtl: ['الشريط والرقم الشبحي يُقاسان من بداية القراءة ونهايتها', 'لا أحرف كبيرة ولا تباعد حروف', 'الأرقام غربية حسب الهوية'],
    provenance: [
      {
        source: sourceRef('image-text-layout/style-directions'),
        extracted: ['اتجاه «Business Innovation»: كتل عناوين جريئة ونظيفة، تباين كبير بين العنوان والنص، منطق مرقّم، لون تمييز واثق', 'تجنّب لغة الإعلانات الصاخبة'],
        adapted: ['الملصقات الإنجليزية الصغيرة (SIGNAL, MOVE) استُبدلت بلا شيء: لا كلمات إنجليزية في التصميم'],
        notUsed: ['مقترحات الاتجاهات الثلاثة للمستخدم (هنا الأسلوب يُختار من المكتبة)'],
      },
      {
        source: sourceRef('carousel-generator/design-system'),
        extracted: ['رقم شبحي بشفافية منخفضة جدًا (4%) في شرائح المحتوى، ولا رقم شبحي في شرائح الخطوات', 'علامة تمييز قصيرة على حافة البطاقة لا بطولها كاملًا'],
        adapted: ['البرتقالي #E85D04 استُبدل بأزرق الهوية', 'Inter استُبدل بـ Cairo/Tajawal', 'شفافية الرقم 5% لتظهر على الأبيض', 'الرقم الشبحي في الصفحات المفتوحة فقط (جملة، اقتباس، منشور): البطاقات تخفيه وتترك منه قطعة', 'علامة البطاقة على حافة بداية القراءة (اليمين) وبطول الثلث'],
        notUsed: ['تباعد الحروف السالب', 'الأحرف الكبيرة', 'خط Caveat المكتوب باليد', 'ارتفاع السطر 0.97 للعناوين (يقص التشكيل العربي)'],
      },
    ],
    designedHere: ['الغلاف والخاتمة بالأزرق الليلي المشتق من الهوية', 'شريط تمييز بعرض نصف الصفحة من بداية القراءة', 'أرقام القوائم بيضاء على مربعات بلون التمييز (الأرقام الملونة على السطح لا تبلغ 4.5 حين تصغر)'],
    keepCompositionDecor: false,
  },
  {
    kind: 'style',
    id: 'swiss-editorial',
    version: 1,
    status: 'reusable',
    family: 'grid',
    name: 'سويسري تحريري',
    purpose: 'شرح منظّم وخطوات وأطر عمل: كل شيء على عمود واحد يبدأ من أعلى الصفحة، بلا بطاقات ولا زوايا، وعمود تمييز رأسي',
    tone: 'دقيق، منظّم، هادئ الألوان',
    distinctFrom: { style: 'quiet-editorial', how: 'المحتوى يبدأ من أعلى الصفحة لا مائلًا، البنود بخطوط فاصلة لا بطاقات، بلا أي زوايا مستديرة، التمهيد نص بلا إطار، وعمود تمييز رأسي عند بداية القراءة بدل الخط الأفقي' },
    tokens: {
      light: { bg: '#FFFFFF', surface: '#F4F5F6', text: '#111111', muted: '#55595F' },
    },
    defaultMode: 'light',
    type: { titleScale: 0.95, titleWeight: 'bold', titleLineHeight: 1.35 },
    treatment: { pillRadius: 0, pillFill: 'outline', kicker: 'plain', cardMode: 'rule', cardRadius: 0, badge: 'plain', ruleFill: '@text', ruleRadius: 0, rule: { width: 72, height: 8 }, artRadius: 0 },
    layout: { stackAlign: 'start', margin: 112, maxScale: 1.15 },
    decor: {
      cover: [{ shape: 'rect', at: 'start', x: 52, y: 'R', w: 16, h: 'F-R', fill: '@accent', name: 'عمود التمييز' }],
      content: [{ shape: 'rect', at: 'start', x: 56, y: 'R', w: 8, h: 'F-R', fill: '@accent', name: 'عمود التمييز' }],
      cta: [{ shape: 'rect', at: 'start', x: 52, y: 'R', w: 16, h: 'F-R', fill: '@accent', name: 'عمود التمييز' }],
    },
    densities: ['comfortable', 'dense'],
    // Roles not claimed, and why (a design decision, not a test result).
    notFor: { quote: 'الاقتباس يحتاج مساحة وسطية وإيقاعًا هادئًا؛ في العمود الصارم يصير سطرًا عاديًا', collage: 'القصاصات المائلة بأشرطتها اللاصقة لغة بصرية مستقلة؛ لا تُدمج مع هذا الأسلوب' },
    roles: ['cover', 'list', 'steps', 'framework', 'comparison', 'evidence', 'statement', 'cta'],
    formats: ['portrait', 'story'],
    rtl: ['العمود الرأسي عند بداية القراءة (اليمين)', 'كل النصوص تبدأ من اليمين', 'لا تباعد حروف'],
    provenance: [
      {
        source: sourceRef('image-text-layout/style-directions'),
        extracted: ['اتجاه «Finance Explainer»: شبكة نظيفة، أقسام مرقّمة، فواصل واضحة، لون مقيّد', 'الحمض البصري: سطح أبيض، حبر أسود، خطوط وحدات رمادية ناعمة، شرائط تمييز رأسية، لون تمييز واحد'],
        adapted: ['الجداول والرسوم الصغيرة لم تُنقل: التكوينات الحالية تحمل البنود والأطر'],
        notUsed: ['الملصقات الإنجليزية الصغيرة', 'التسميات بالصينية'],
      },
      {
        source: sourceRef('opendesign/editorial'),
        extracted: ['الحبر #111111 للنص الأساسي', 'لا تسوية للتسلسل الهرمي بحجم ووزن واحد لكل النصوص', 'المسافات قبل الحدود والظلال'],
        adapted: ['خط Gelasio المذيّل استُبدل بـ Cairo'],
        notUsed: ['ألوان النجاح والتحذير والخطر (الهوية لا تستعمل البرتقالي)'],
      },
    ],
    designedHere: ['عمود التمييز الرأسي بطول منطقة المحتوى', 'المحتوى من أعلى المنطقة', 'هامش جانبي 112'],
    referenceOnly: ['pangxiaobin/MarkCardStudio (GPL-3.0) فيه ملف theme-swiss-grid.css: لم يُفتح ولم يُنقل منه شيء، والأسلوب لا يحمل اسمه؛ «سويسري» وصف لمدرسة تصميم عامة'],
    keepCompositionDecor: false,
  },
  {
    kind: 'style',
    id: 'newspaper-editorial',
    version: 1,
    status: 'reusable',
    family: 'editorial',
    name: 'صحفي',
    purpose: 'رأي وتحليل واقتباسات: ترويسة بخطين أسودين، عناوين سوداء ثقيلة، بنود مفصولة بخطوط، والتمييز في التمهيد وكلمة العنوان فقط',
    tone: 'جاد، تحليلي، بالحبر الأسود',
    distinctFrom: { style: 'swiss-editorial', how: 'ترويسة أفقية مزدوجة سوداء بدل العمود الملوّن، عناوين أثقل وأكبر، أرقام كبيرة بالحبر الأسود، وخط سفلي يغلق الغلاف؛ والتمييز لا يظهر في الزخرفة' },
    tokens: {
      light: { bg: '#FFFFFF', surface: '#F3F3F1', text: '#141414', muted: '#575757' },
    },
    defaultMode: 'light',
    type: { titleScale: 1.08, titleWeight: 'black', titleLineHeight: 1.3 },
    treatment: { pillRadius: 0, pillFill: 'outline', kicker: 'plain', cardMode: 'rule', cardRadius: 0, badge: 'plain', ruleFill: '@text', ruleRadius: 0, rule: { width: 120, height: 3 }, artRadius: 0, figureColor: '@text' },
    layout: { stackAlign: 'start', margin: 96, maxScale: 1.15 },
    decor: {
      cover: [
        { shape: 'rect', at: 'start', x: 'M', y: 'R-64', w: 'W-2*M', h: 8, fill: '@text', name: 'ترويسة (خط سميك)' },
        { shape: 'rect', at: 'start', x: 'M', y: 'R-48', w: 'W-2*M', h: 2, fill: '@text', name: 'ترويسة (خط رفيع)' },
        { shape: 'rect', at: 'start', x: 'M', y: 'F+24', w: 'W-2*M', h: 2, fill: '@text', name: 'خط الإغلاق' },
      ],
      content: [
        { shape: 'rect', at: 'start', x: 'M', y: 'R-56', w: 'W-2*M', h: 6, fill: '@text', name: 'ترويسة (خط سميك)' },
        { shape: 'rect', at: 'start', x: 'M', y: 'R-44', w: 'W-2*M', h: 2, fill: '@text', name: 'ترويسة (خط رفيع)' },
      ],
      cta: [
        { shape: 'rect', at: 'start', x: 'M', y: 'R-56', w: 'W-2*M', h: 6, fill: '@text', name: 'ترويسة (خط سميك)' },
        { shape: 'rect', at: 'start', x: 'M', y: 'R-44', w: 'W-2*M', h: 2, fill: '@text', name: 'ترويسة (خط رفيع)' },
      ],
    },
    densities: ['comfortable', 'dense'],
    // Roles not claimed, and why (a design decision, not a test result).
    notFor: { collage: 'القصاصات المائلة بأشرطتها اللاصقة لغة بصرية مستقلة؛ لا تُدمج مع هذا الأسلوب' },
    roles: ['cover', 'list', 'quote', 'statement', 'evidence', 'comparison', 'framework', 'steps', 'cta'],
    formats: ['portrait', 'story'],
    rtl: ['الترويسة بعرض المنطقة كاملة', 'التمهيد نص بلا إطار عند بداية القراءة', 'لا أحرف كبيرة ولا تباعد حروف'],
    provenance: [
      {
        source: sourceRef('image-text-layout/style-directions'),
        extracted: ['اتجاه «Opinion Column»: أعمدة مقيّدة، هوامش واسعة، اقتباس بارز، تمييز قليل'],
        adapted: ['المصدر يتجنب الخطوط الأفقية الكاملة افتراضيًا؛ هنا اخترناها عمدًا لهذا الأسلوب وحده لأنها علامة الصحيفة، ولم نضفها إلى غيره'],
        notUsed: ['الرسوم التوضيحية الأدبية'],
      },
      {
        source: sourceRef('opendesign/editorial'),
        extracted: ['الحبر #111111 والنص #111827', 'تسلسل واضح: عنوان ← نص داعم ← إجراء'],
        adapted: ['النص #141414 والرمادي #575757 ليبلغا 4.5 على الأبيض والسطح'],
        notUsed: ['Gelasio وUbuntu Mono'],
      },
    ],
    designedHere: ['الترويسة المزدوجة (خط سميك فوق رفيع)', 'خط إغلاق أسفل الغلاف', 'التمييز في النص لا في الزخرفة', 'الأرقام الكبيرة بالحبر الأسود'],
    keepCompositionDecor: false,
  },
  {
    kind: 'style',
    id: 'monochrome-editorial',
    version: 1,
    status: 'reusable',
    family: 'monochrome',
    name: 'أحادي ليلي',
    purpose: 'محتوى تأملي واقتباسات وأفكار هادئة على صفحات بلون واحد: الأزرق الليلي المشتق من الهوية بتدرجاته، داخل إطار رفيع',
    tone: 'هادئ، ليلي، مركّز',
    distinctFrom: { style: 'quiet-editorial', how: 'كل الصفحات داكنة بلون واحد (الأزرق الليلي) وتدرجاته، إطار رفيع حول الصفحة، شارات دائرية بإطار، والمحتوى في الوسط' },
    tokens: {
      dark: { bg: '#0E2A5C', surface: '#16386F', text: '#F5F8FC', muted: '#B8C6DA' },
    },
    defaultMode: 'dark',
    type: { titleScale: 1.05, titleWeight: 'bold', titleLineHeight: 1.35 },
    treatment: { pillRadius: 'full', pillFill: 'outline', cardMode: 'outline', cardRadius: 20, badge: 'ellipse', ruleFill: '@accent', ruleRadius: 3, rule: { width: 120, height: 6 }, artRadius: 20 },
    layout: { stackAlign: 'center', margin: 112 },
    decor: {
      cover: [{ shape: 'frame', x: 44, y: 'T+44', w: 'W-88', h: 'H-T-B-88', stroke: '@muted', strokeWidth: 2, opacity: 0.5, name: 'إطار الصفحة' }],
      content: [{ shape: 'frame', x: 44, y: 'T+44', w: 'W-88', h: 'H-T-B-88', stroke: '@muted', strokeWidth: 2, opacity: 0.5, name: 'إطار الصفحة' }],
      cta: [{ shape: 'frame', x: 44, y: 'T+44', w: 'W-88', h: 'H-T-B-88', stroke: '@muted', strokeWidth: 2, opacity: 0.5, name: 'إطار الصفحة' }],
    },
    densities: ['airy', 'comfortable'],
    // Roles not claimed, and why (a design decision, not a test result).
    notFor: { comparison: 'المقارنة تعتمد على تلوين الجهة الإيجابية؛ في الصفحة أحادية اللون يضعف الفرق', collage: 'القصاصات المائلة بأشرطتها اللاصقة لغة بصرية مستقلة؛ لا تُدمج مع هذا الأسلوب' },
    roles: ['cover', 'list', 'quote', 'statement', 'steps', 'evidence', 'framework', 'cta'],
    formats: ['portrait', 'story'],
    rtl: ['الإطار متناظر', 'الشارات في بداية القراءة', 'لا تباعد حروف'],
    provenance: [
      {
        source: sourceRef('image-text-layout/style-directions'),
        extracted: ['وحدات مؤطّرة مدمجة', 'لون تمييز واحد مقيّد'],
        adapted: ['السطح الأبيض الافتراضي في المصدر عُكس هنا عمدًا: الأسلوب ليلي ويُستعمل حين يُطلب الداكن'],
        notUsed: ['تحذير المصدر من الخلفيات الملوّنة ينطبق على الخلفيات الدافئة؛ الأزرق الليلي من الهوية'],
      },
    ],
    designedHere: ['الصفحة بالأزرق الليلي المشتق من الهوية', 'لون التمييز يُفتَّح على الداكن ليبلغ 4.5 ويُسجَّل', 'إطار رفيع بنصف شفافية'],
    keepCompositionDecor: false,
  },
  {
    kind: 'style',
    id: 'collage-cutout',
    version: 1,
    status: 'reusable',
    family: 'collage',
    name: 'كولاج تحريري',
    purpose: 'كاروسيل تحريري بقصاصات ورقية: ورقة مائلة قليلًا خلف المحتوى وشريط لاصق، وصفحات تتناوب بين الداكن والفاتح',
    tone: 'حيوي، شخصي، مرتّب رغم القصاصات',
    distinctFrom: { style: 'magazine-bold', how: 'ورقة مائلة خلف المحتوى وشريط لاصق بدل الأشرطة المستقيمة، تناوب داكن/فاتح من الغلاف، بطاقات بيضاء على الورقة، وموجة يدوية أسفل صفحات المحتوى' },
    tokens: {
      light: { bg: '#FFFFFF', surface: '#E9F0F8', text: '#14181F', muted: '#4E5866' },
      dark: { bg: '#0E2A5C', surface: '#1B4282', text: '#FFFFFF', muted: '#C7D3E4' },
    },
    defaultMode: 'alternate',
    alternateStart: 'dark',
    type: { titleScale: 1.05, titleWeight: 'black', titleLineHeight: 1.3 },
    treatment: { pillRadius: 4, pillFill: '@accent', cardMode: 'fill', cardFill: '@bg', cardRadius: 6, badge: 'rect', ruleFill: '@accent', ruleRadius: 2, rule: { width: 140, height: 12 }, artRadius: 6 },
    layout: { stackAlign: 'center', margin: 120 },
    decor: {
      cover: [
        { shape: 'rect', at: 'start', x: 'M-48', y: 'R-56', w: 'W-2*M+96', h: 'F-R+104', fill: '@surface', radius: 6, rotation: -1.6, name: 'ورقة القصاصة' },
        { shape: 'rect', at: 'start', x: 'M+24', y: 'R-78', w: 160, h: 40, fill: '@accent', opacity: 0.85, radius: 3, rotation: -8, name: 'شريط لاصق' },
      ],
      content: [
        { shape: 'rect', at: 'start', x: 'M-44', y: 'R-48', w: 'W-2*M+88', h: 'F-R+88', fill: '@surface', radius: 6, rotation: 1.1, name: 'ورقة القصاصة' },
        { shape: 'rect', at: 'end', x: 'M+24', y: 'R-70', w: 150, h: 38, fill: '@accent', opacity: 0.85, radius: 3, rotation: 7, name: 'شريط لاصق' },
      ],
      cta: [
        { shape: 'rect', at: 'start', x: 'M-48', y: 'R-56', w: 'W-2*M+96', h: 'F-R+104', fill: '@surface', radius: 6, rotation: -1.2, name: 'ورقة القصاصة' },
        { shape: 'rect', at: 'start', x: 'M+24', y: 'R-78', w: 160, h: 40, fill: '@accent', opacity: 0.85, radius: 3, rotation: -8, name: 'شريط لاصق' },
      ],
    },
    densities: ['comfortable'],
    // Roles not claimed, and why (a design decision, not a test result).
    notFor: {},
    roles: ['cover', 'collage', 'list', 'quote', 'statement', 'steps', 'framework', 'evidence', 'comparison', 'cta'],
    formats: ['portrait', 'story'],
    rtl: ['الشريط اللاصق على بداية القراءة في الغلاف وعلى نهايتها في المحتوى', 'ميل الورقة أقل من درجتين فلا تميل الأسطر', 'لا ملصقات ولا رموز تعبيرية'],
    provenance: [
      {
        source: sourceRef('image-text-layout/style-directions'),
        extracted: ['تحذير المصدر من «ملصقات القصاصات» والفوضى'],
        adapted: ['الكولاج هنا ورقة واحدة وشريط لاصق فقط، والنص يبقى أفقيًا على سطح هادئ'],
        notUsed: ['الملصقات والرموز التعبيرية والأسهم الصاخبة'],
      },
      { source: null, designedHere: true, note: 'طلب «Editorial Collage» مع تناوب داكن/فاتح من موجز المستخدم (2026-10-02)' },
    ],
    designedHere: ['ورقة مائلة خلف المحتوى بلون السطح', 'شريط لاصق بلون التمييز', 'بطاقات بيضاء على الورقة', 'تناوب داكن/فاتح يبدأ بالغلاف الداكن'],
    keepCompositionDecor: false,
  },
  {
    kind: 'style',
    id: 'quiet-minimal',
    version: 1,
    status: 'reusable',
    family: 'minimal',
    name: 'بسيط هادئ',
    purpose: 'جملة أو فكرة واحدة بمسافات واسعة جدًا: النص في الوسط، بلا بطاقات، ونقطة تمييز صغيرة فقط',
    tone: 'صامت، متأمل، واسع',
    distinctFrom: { style: 'quiet-editorial', how: 'النص في الوسط لا عند بداية القراءة، عناوين أصغر بمسافات أوسع (هامش 128)، بلا خطوط علوية ولا بطاقات، ونقطة صغيرة في أسفل الوسط بدل الشريط' },
    tokens: {
      light: { bg: '#FFFFFF', surface: '#F4F4F1', text: '#0C0C09', muted: '#5E5E58' },
    },
    defaultMode: 'light',
    type: { titleScale: 0.9, titleWeight: 'bold', titleLineHeight: 1.45, align: 'center' },
    treatment: { pillRadius: 'full', pillFill: 'outline', kicker: 'plain', cardMode: 'rule', badge: 'plain', ruleFill: '@accent', ruleRadius: 3, rule: { width: 48, height: 6 }, artRadius: 24 },
    layout: { stackAlign: 'center', margin: 128, maxScale: 1.15 },
    decor: {
      cover: [{ shape: 'ellipse', at: 'start', x: '(W-20)/2', y: 'F+36', w: 20, h: 20, fill: '@accent', name: 'علامة النهاية' }],
      cta: [{ shape: 'ellipse', at: 'start', x: '(W-20)/2', y: 'F+36', w: 20, h: 20, fill: '@accent', name: 'علامة النهاية' }],
    },
    densities: ['airy'],
    // Roles not claimed, and why (a design decision, not a test result).
    notFor: { comparison: 'تحتاج بطاقتين متجاورتين؛ الأسلوب بلا بطاقات وموسّط', framework: 'الإطار شبكة بطاقات؛ الأسلوب بلا بطاقات', collage: 'القصاصات المائلة بأشرطتها اللاصقة لغة بصرية مستقلة؛ لا تُدمج مع هذا الأسلوب' },
    roles: ['cover', 'quote', 'statement', 'list', 'steps', 'evidence', 'cta'],
    formats: ['portrait', 'story'],
    rtl: ['التوسيط للنصوص القصيرة فقط؛ البنود تبقى من بداية القراءة', 'لا تباعد حروف'],
    provenance: [
      {
        source: sourceRef('opendesign/minimal'),
        extracted: ['السطح #F4F4F1 والحبر #0C0C09', 'المسافات قبل الحدود والظلال', 'مقياس المسافات 4/8/12/16/24/32'],
        adapted: ['الحبر #0C0C09 للنص، والرمادي #5E5E58 ليبلغ 4.5', 'المقياس «expressive» بلا قيم في المصدر: لم نخترع له قيمًا'],
        notUsed: ['Inter وOpen Sans', 'اللون الثانوي #312C85'],
      },
      {
        source: sourceRef('image-text-layout/style-directions'),
        extracted: ['اتجاه «Opinion Column»: هوامش واسعة وتمييز قليل'],
        adapted: [],
        notUsed: ['الأعمدة المتعددة'],
      },
    ],
    designedHere: ['نقطة تمييز في أسفل الوسط علامةَ نهاية للغلاف والخاتمة', 'هامش 128', 'توسيط النصوص', 'القائمة البسيطة تتوسّط كتلةً وتبقى بنودها من بداية القراءة'],
    keepCompositionDecor: false,
  },
  {
    kind: 'style',
    id: 'geometric-editorial',
    version: 1,
    status: 'reusable',
    family: 'geometric',
    name: 'هندسي',
    purpose: 'محتوى تعليمي حيوي: دوائر صلبة بلون التمييز تخرج من حافة الصفحة، بطاقات مربعة مملوءة وشارات أرقام دائرية',
    tone: 'حيوي، ودود، واضح',
    distinctFrom: { style: 'magazine-bold', how: 'أشكال دائرية صلبة تخرج من حافة الصفحة بدل الأشرطة والرقم الشبحي، بطاقات مملوءة بلا علامة، شارات أرقام دائرية، كل الصفحات فاتحة؛ وعن الأسلوب الكلاسيكي: بطاقات بزوايا حادة وأشكال صلبة لا شفافة' },
    tokens: {
      light: { bg: '#FFFFFF', surface: '#EAF1FA', text: '#101828', muted: '#4B5563' },
    },
    defaultMode: 'light',
    type: { titleScale: 1.05, titleWeight: 'black', titleLineHeight: 1.3 },
    treatment: { pillRadius: 'full', pillFill: '@accent', cardMode: 'fill', cardRadius: 0, badge: 'ellipse', ruleFill: '@accent', ruleRadius: 8, rule: { width: 96, height: 16 }, artRadius: 0 },
    layout: { stackAlign: 'center', margin: 96 },
    decor: {
      cover: [
        { shape: 'ellipse', at: 'end', x: -150, y: 'F+10', w: 480, h: 480, fill: '@accent', sequence: 'single', name: 'دائرة صلبة' },
        // In a carousel the swipe button sits there: a pale circle keeps it readable.
        { shape: 'ellipse', at: 'end', x: -150, y: 'F+10', w: 480, h: 480, fill: '@surface', sequence: 'carousel', name: 'دائرة بلون السطح' },
        { shape: 'rect', at: 'start', x: -70, y: 'T-70', w: 260, h: 260, fill: '@surface', rotation: 45, name: 'مربع مائل' },
      ],
      content: [
        { shape: 'ellipse', at: 'start', x: 'M', y: 'R-96', w: 44, h: 44, fill: '@accent', name: 'دائرة صغيرة' },
        { shape: 'rect', at: 'start', x: 'M+52', y: 'R-96', w: 44, h: 44, fill: '@surface', name: 'مربع صغير' },
      ],
      cta: [{ shape: 'ellipse', at: 'end', x: -150, y: 'F+10', w: 480, h: 480, fill: '@accent', name: 'دائرة صلبة' }],
    },
    densities: ['comfortable'],
    // Roles not claimed, and why (a design decision, not a test result).
    notFor: { quote: 'الأشكال الصلبة الكبيرة تنافس نص الاقتباس على الانتباه', collage: 'القصاصات المائلة بأشرطتها اللاصقة لغة بصرية مستقلة؛ لا تُدمج مع هذا الأسلوب' },
    roles: ['cover', 'list', 'steps', 'framework', 'evidence', 'statement', 'comparison', 'cta'],
    formats: ['portrait', 'story'],
    rtl: ['الدائرة الكبيرة عند نهاية القراءة (اليسار) بعيدًا عن شارة الحساب', 'الأشكال الصغيرة من بداية القراءة'],
    provenance: [
      {
        source: sourceRef('image-text-layout/style-directions'),
        extracted: ['اتجاه «Business Innovation»: رسوم بسيطة ولون تمييز واثق'],
        adapted: ['الرسوم البسيطة صارت أشكالًا هندسية صلبة على حواف الصفحة'],
        notUsed: ['التدرجات اللونية والأيقونات ثلاثية الأبعاد (المصدر يمنعها أيضًا)'],
      },
      { source: null, designedHere: true, note: 'الأشكال وأماكنها صُممت هنا لصفحات عربية' },
    ],
    designedHere: ['دائرة صلبة تخرج من أسفل نهاية الصفحة (بلون السطح في غلاف الكاروسيل حيث زر السحب)', 'مربع مائل بلون السطح في أعلى البداية', 'زوج دائرة ومربع فوق المحتوى'],
    keepCompositionDecor: false,
  },
  {
    kind: 'style',
    id: 'mint-highlight',
    version: 1,
    status: 'reusable',
    family: 'educational',
    name: 'تعليمي بتظليل نعناعي',
    purpose: 'كاروسيلات تعليمية واضحة: خلفية بيضاء، عناوين سوداء عريضة، تظليل نعناعي خلف الكلمة المهمة، إطارات رفيعة وأسهم خفيفة، وفكرة واحدة في كل شريحة',
    tone: 'هادئ، واضح، تعليمي، بلا زحمة',
    distinctFrom: { style: 'quiet-minimal', how: 'الكلمة المهمة على شريط تظليل نعناعي بلون النص لا بلون التمييز، إطارات رفيعة ولوحات مظلّلة وسهم نازل بين المراحل، عدّاد «1/10» نصّي واسم الحساب وحده في التذييل ودعوة سحب نصّية بلا زر، والنص من بداية القراءة لا في الوسط' },
    // Green is the identity's functional colour; this style is built on it
    // (the creator's reference asks for a mint marker). Under an identity
    // without a green role it keeps its own.
    accentRole: 'positive',
    tokens: {
      light: { bg: '#FFFFFF', surface: '#F3F7F5', text: '#14181F', muted: '#4A515A', accent: '#10B981', highlight: 0.84, line: '#E1E6E9' },
    },
    defaultMode: 'light',
    type: { titleScale: 1, titleWeight: 'black', titleLineHeight: 1.35, headingFont: 'cairo', bodyFont: 'tajawal' },
    treatment: {
      accentMode: 'highlight',
      kicker: 'plain',
      pillFill: '@highlight',
      pillText: '@text',
      pillRadius: 8,
      cardMode: 'outline',
      cardStroke: '@line',
      cardRadius: 8,
      badge: 'plain',
      rule: { width: 'full', height: 2 },
      ruleFill: '@line',
      ruleRadius: 0,
      figureColor: '@text',
      boxRadius: 8,
      artRadius: 8,
    },
    // The creator's type scale: cover title 116, titles 88, body 44 px at
    // 1080 wide (brief: 90–120 / 70–90 / 42–55); short pages keep these
    // sizes and gain white space instead of growing.
    layout: { stackAlign: 'center', margin: 96, capScale: 1 },
    chrome: {
      look: { bar: false, counter: 'plain', swipe: 'text', badge: 'name' },
      defaults: { pagination: { style: 'fraction' }, swipe: { text: 'اسحب واكتشف', lastText: '' } },
    },
    decor: {},
    densities: ['comfortable'],
    // Roles not claimed, and why (a design decision, not a test result).
    notFor: { collage: 'القصاصات المائلة بأشرطتها اللاصقة تخالف هدوء الأسلوب التعليمي' },
    roles: ['cover', 'cover-figure', 'concept', 'flow', 'list', 'steps', 'evidence', 'framework', 'comparison', 'quote', 'statement', 'cta', 'cta-actions'],
    formats: ['portrait'],
    rtl: ['التظليل يغطي النصف السفلي من الكلمة ويمتد قليلًا عن طرفيها، فلا يقطع نقاط الحروف ولا علاماتها', 'العدّاد ودعوة السحب عند نهاية القراءة (اليسار)، واسم الحساب عند بدايتها', 'سهم المراحل نازل لا جانبي، فلا يحتاج قلبًا'],
    provenance: [
      {
        source: null,
        reference: { kind: 'creator-reference', at: '2026-10-03', what: 'صورة كاروسيل مرجعية من 10 شرائح ووصف «DNA بصري» في طلب صاحب الحساب' },
        extracted: ['خلفية بيضاء وعناوين سوداء عريضة', 'تظليل نعناعي خلف الكلمة المهمة', 'إطار رفيع حول فكرة، ولوح مظلّل، وشريط خلاصة مظلّل', 'مربعان بينهما دائرة بسهم نازل', 'صفّا إجراء بعرض الصفحة في الخاتمة', 'عدّاد «1/10» واسم الحساب ودعوة «اسحب واكتشف» نصوصًا صغيرة'],
        adapted: ['الأخضر من الدور الوظيفي في الهوية (#10B981)، مُعتَّم للنص حتى تباين 4.5، والتظليل خليط منه مع الأبيض', 'الخطّان Cairo وTajawal من الهوية', 'أحجام العناوين والمتن من قواعد الطلب (الغلاف 116، العناوين 88، المتن 44 بكسل على عرض 1080) ولا تكبر الصفحة القصيرة فوقها'],
        notUsed: ['نصوص الصورة المرجعية: كُتب نص المثال من جديد'],
      },
    ],
    designedHere: ['التظليل في النصف السفلي من السطر بلون النص', 'شريط تظليل بعرض العمود خلف الرقم الكبير', 'سماكة الإطار 2 وزواياه 8', 'العدّاد ودعوة السحب واسم الحساب نصوصًا بلا خلفيات'],
    keepCompositionDecor: false,
  },
];
