// Every signal the platform engines can emit. Each entry says:
//   provenance   where the value comes from (derived = measured from the
//                content, heuristic = a rule-of-thumb estimate, historical =
//                the account's own results)
//   relevance    why the signal matters on that platform, with its own
//                provenance and sources (official system cards, public code)
//   category     positive_engagement | negative_feedback | attention |
//                quality | format | context | historical
// The registry (core/signal-registry.js) loads this catalog, applies the
// configuration's switches and weights, and is the only place engines look
// signals up, so a signal can be renamed, retired or re-sourced here.

const S = (id, platform, category, provenance, relevance, label, description) => ({ id, platform, category, provenance, relevance, label, description, enabled: true });
const rel = (provenance, sources, note) => ({ provenance, sources, note });

const X_ACTION = (action) => rel('public-source-code', ['x-algorithm'], `X's ranker predicts P(${action}) per viewer (home-mixer/params/param.rs). Basira estimates the content's potential for it; no viewer-level prediction is made.`);

export const SIGNAL_CATALOG = [
  // ---------------------------------------------------------------- X
  S('x.hook_strength', 'x', 'attention', 'heuristic', rel('heuristic', ['basira-heuristics'], 'The opening decides whether a reader dwells; X predicts dwell and not-dwelled.'), { ar: 'قوة الافتتاحية', en: 'Opening strength' }, 'Length, curiosity, specificity, direct address and tension of the first line.'),
  S('x.opening_fit', 'x', 'format', 'derived', rel('heuristic', ['basira-heuristics'], 'A long first sentence delays the claim in a fast-scrolling feed.'), { ar: 'طول الجملة الأولى', en: 'Opening sentence length' }, 'Words in the first sentence against the configured range.'),
  S('x.length_fit', 'x', 'format', 'derived', rel('official', ['x-api-metrics'], '280 characters per post without a subscription (X counts URLs as 23, emoji as 2).'), { ar: 'ملاءمة الطول', en: 'Length fit' }, 'Weighted length within the post limit, or thread posts within it.'),
  S('x.like_potential', 'x', 'positive_engagement', 'heuristic', X_ACTION('favorite'), { ar: 'قابلية الإعجاب', en: 'Like potential' }, 'Opening strength, clarity and moderate emotion.'),
  S('x.reply_potential', 'x', 'positive_engagement', 'heuristic', X_ACTION('reply'), { ar: 'قابلية الرد', en: 'Reply potential' }, 'Questions, opinion, direct address, a specific prompt.'),
  S('x.repost_potential', 'x', 'positive_engagement', 'heuristic', X_ACTION('retweet'), { ar: 'قابلية إعادة النشر', en: 'Repost potential' }, 'Share-worthiness and quotable lines.'),
  S('x.quote_potential', 'x', 'positive_engagement', 'heuristic', X_ACTION('quote'), { ar: 'قابلية الاقتباس', en: 'Quote potential' }, 'A stance others want to add to: opinion, quotable claim.'),
  S('x.share_potential', 'x', 'positive_engagement', 'heuristic', X_ACTION('share / share via DM / copy link'), { ar: 'قابلية المشاركة', en: 'Share potential' }, 'Useful, specific content people send to someone.'),
  S('x.bookmark_potential', 'x', 'positive_engagement', 'heuristic', rel('official', ['x-api-metrics'], 'bookmark_count is an official public metric; its ranking weight is not in the public code.'), { ar: 'قابلية الحفظ', en: 'Bookmark potential' }, 'Reference value: lists, steps, numbers.'),
  S('x.profile_click_potential', 'x', 'positive_engagement', 'heuristic', X_ACTION('profile click'), { ar: 'زيارة الملف الشخصي', en: 'Profile-click potential' }, 'Personal insight, a series, specific expertise.'),
  S('x.follow_potential', 'x', 'positive_engagement', 'heuristic', X_ACTION('follow author'), { ar: 'قابلية المتابعة', en: 'Follow potential' }, 'Profile-click potential plus consistency with the account\'s topics when history exists.'),
  S('x.dwell_potential', 'x', 'attention', 'heuristic', X_ACTION('dwell / dwell time'), { ar: 'زمن البقاء', en: 'Dwell potential' }, 'Enough substance to read, structured with line breaks or a list.'),
  S('x.click_potential', 'x', 'positive_engagement', 'heuristic', X_ACTION('click / open link'), { ar: 'قابلية النقر', en: 'Click potential' }, 'Only when the post has a link: curiosity and specificity of the setup.'),
  S('x.clarity', 'x', 'quality', 'derived', rel('research', ['osman-readability'], 'Readable sentences; Arabic readability proxy.'), { ar: 'الوضوح', en: 'Clarity' }, 'Sentence length and long-word ratio.'),
  S('x.specificity', 'x', 'quality', 'derived', rel('heuristic', ['basira-heuristics'], 'Concrete numbers and units make claims checkable and shareable.'), { ar: 'التحديد', en: 'Specificity' }, 'Numbers, units, few vague words.'),
  S('x.novelty', 'x', 'quality', 'heuristic', rel('public-source-code', ['x-algorithm'], 'X weighs a "post unexplored" head; Basira can only estimate novelty from cues or an AI judgement.'), { ar: 'الجِدّة', en: 'Novelty' }, 'Myth-busting, contrast and research cues (or AI judgement).'),
  S('x.negative_feedback_risk', 'x', 'negative_feedback', 'heuristic', X_ACTION('not interested / mute / block / report'), { ar: 'خطر التفاعل السلبي', en: 'Negative-feedback risk' }, 'Engagement bait, hostile words, curiosity without substance, hashtag and mention excess.'),
  S('x.author_affinity', 'x', 'historical', 'historical', rel('public-source-code', ['the-algorithm', 'x-algorithm'], 'Real-graph style affinity: viewers who engaged with an author before are likelier to again. Measured here as the topic\'s performance on this account.'), { ar: 'ألفة الجمهور بالموضوع', en: 'Audience-topic affinity' }, 'This topic\'s median outcome against the account baseline.'),
  S('x.network_relevance', 'x', 'context', 'historical', rel('public-source-code', ['x-algorithm'], 'In-network versus out-of-network reach is decided per viewer from the follow graph, which creators cannot see.'), { ar: 'الملاءمة الشبكية', en: 'Network relevance' }, 'Requires follower-graph data that X does not expose to creators: always unavailable.'),
  S('x.historical_performance', 'x', 'historical', 'historical', rel('historical', ['account-history'], 'Patterns that beat this account\'s own baseline.'), { ar: 'أداء الحساب التاريخي', en: 'Historical performance' }, 'Matching account patterns, weighted by their confidence.'),

  // ---------------------------------------------------------- Instagram
  S('instagram.hook_strength', 'instagram', 'attention', 'heuristic', rel('official', ['meta-ig-feed-card'], 'Instagram predicts whether you skip a post and whether you spend more than 10 seconds on the first post.'), { ar: 'قوة الغلاف', en: 'Cover strength' }, 'The cover (or first line): length, curiosity, specificity, address.'),
  S('instagram.share_potential', 'instagram', 'positive_engagement', 'heuristic', rel('official', ['meta-ig-feed-card', 'instagram-ranking-explained'], 'Instagram predicts sharing a post in a direct message (Feed) and resharing a reel (Reels).'), { ar: 'قابلية الإرسال والمشاركة', en: 'Share potential' }, 'Usefulness, specificity, novelty, quotable lines.'),
  S('instagram.save_potential', 'instagram', 'positive_engagement', 'heuristic', rel('official', ['ig-graph-media-insights'], '"saved" is an official media metric; its ranking weight is not published.'), { ar: 'قابلية الحفظ', en: 'Save potential' }, 'Reference value: steps, lists, density in range, depth.'),
  S('instagram.comment_potential', 'instagram', 'positive_engagement', 'heuristic', rel('official', ['instagram-ranking-explained'], 'Feed predictions include how likely you are to comment.'), { ar: 'قابلية التعليق', en: 'Comment potential' }, 'Questions, specific prompts, opinion, direct address.'),
  S('instagram.profile_visit_potential', 'instagram', 'positive_engagement', 'heuristic', rel('official', ['meta-ig-feed-card', 'instagram-ranking-explained'], 'Instagram predicts time on the author\'s profile after a post, and tapping the profile photo.'), { ar: 'زيارة الحساب', en: 'Profile-visit potential' }, 'Personal insight, series, specificity.'),
  S('instagram.carousel_completion', 'instagram', 'attention', 'heuristic', rel('official', ['meta-ig-feed-card'], 'Instagram predicts how likely you are to swipe through the whole carousel.'), { ar: 'إكمال الكاروسيل', en: 'Carousel completion' }, 'Slide count in range, density, promise kept, continuity between slides.'),
  S('instagram.time_spent_potential', 'instagram', 'attention', 'heuristic', rel('official', ['meta-ig-feed-card'], 'Instagram predicts how much time you will spend on a post.'), { ar: 'زمن المشاهدة', en: 'Time-spent potential' }, 'Depth and readable density.'),
  S('instagram.skip_risk', 'instagram', 'negative_feedback', 'heuristic', rel('official', ['meta-ig-feed-card'], 'Instagram predicts how likely you are to skip a post.'), { ar: 'خطر التخطي', en: 'Skip risk' }, 'A weak or overloaded cover.'),
  S('instagram.reel_completion', 'instagram', 'attention', 'heuristic', rel('official', ['instagram-ranking-explained'], 'Reels predictions include watching a reel all the way through.'), { ar: 'إكمال الريل', en: 'Reel completion' }, 'Duration in range, rhythm, open loop with a payoff.'),
  S('instagram.reel_hook', 'instagram', 'attention', 'derived', rel('heuristic', ['basira-heuristics'], 'The first seconds decide whether a reel is skipped (reels_skip_rate is an official metric).'), { ar: 'افتتاحية الريل', en: 'Reel opening' }, 'A promise within the first seconds and a short first scene.'),
  S('instagram.content_clarity', 'instagram', 'quality', 'derived', rel('research', ['osman-readability'], 'Readable text on a phone.'), { ar: 'وضوح المحتوى', en: 'Content clarity' }, 'Readability proxy.'),
  S('instagram.specificity', 'instagram', 'quality', 'derived', rel('heuristic', ['basira-heuristics'], 'Concrete claims.'), { ar: 'التحديد', en: 'Specificity' }, 'Numbers, units, few vague words.'),
  S('instagram.visual_density', 'instagram', 'quality', 'derived', rel('official', ['meta-ig-feed-card'], 'Media characteristics such as text overlay are listed signals; Basira measures text load per slide.'), { ar: 'كثافة النص في الشرائح', en: 'Slide text density' }, 'Share of slides within their readable word budget.'),
  S('instagram.caption_fit', 'instagram', 'format', 'heuristic', rel('heuristic', ['basira-heuristics'], 'Captions are truncated in the feed; the first line should carry the point.'), { ar: 'ملاءمة الوصف', en: 'Caption fit' }, 'Caption opening within the preview length.'),
  S('instagram.format_fit', 'instagram', 'format', 'derived', rel('heuristic', ['basira-heuristics'], 'Slide count, reel duration or post length within Basira\'s ranges.'), { ar: 'ملاءمة الصيغة', en: 'Format fit' }, 'Structure of the chosen format.'),
  S('instagram.negative_feedback_risk', 'instagram', 'negative_feedback', 'heuristic', rel('heuristic', ['basira-heuristics'], 'Bait and hostile wording invite hiding or reporting.'), { ar: 'خطر التفاعل السلبي', en: 'Negative-feedback risk' }, 'Engagement bait, hostile words, curiosity without substance.'),
  S('instagram.topic_affinity', 'instagram', 'historical', 'historical', rel('historical', ['account-history'], 'The account\'s results for this topic.'), { ar: 'ألفة الجمهور بالموضوع', en: 'Audience-topic affinity' }, 'This topic\'s median outcome against the account baseline.'),
  S('instagram.historical_performance', 'instagram', 'historical', 'historical', rel('historical', ['account-history'], 'Patterns that beat this account\'s baseline.'), { ar: 'أداء الحساب التاريخي', en: 'Historical performance' }, 'Matching account patterns.'),

  // ----------------------------------------------------------- Facebook
  S('facebook.hook_strength', 'facebook', 'attention', 'heuristic', rel('official', ['meta-fb-feed-card'], 'Facebook predicts whether you scroll past a post rather than engage.'), { ar: 'قوة الافتتاحية', en: 'Opening strength' }, 'First line: length, curiosity, specificity, address.'),
  S('facebook.meaningful_comment_potential', 'facebook', 'positive_engagement', 'heuristic', rel('official', ['meta-fb-feed-card'], 'Comment metrics and the intent to engage with posts from a connection are listed in the system card.'), { ar: 'قابلية التعليق الهادف', en: 'Meaningful-comment potential' }, 'Questions, personal stories, specific prompts.'),
  S('facebook.share_potential', 'facebook', 'positive_engagement', 'heuristic', rel('heuristic', ['basira-heuristics'], 'Shares are a reported post metric; no weight is published.'), { ar: 'قابلية المشاركة', en: 'Share potential' }, 'Usefulness, specificity, relatable lines.'),
  S('facebook.conversation_potential', 'facebook', 'positive_engagement', 'heuristic', rel('official', ['meta-fb-feed-card'], 'Strong intent to interact with connections is a listed prediction.'), { ar: 'قابلية النقاش', en: 'Conversation potential' }, 'Opinion, questions, direct address.'),
  S('facebook.scroll_past_risk', 'facebook', 'negative_feedback', 'heuristic', rel('official', ['meta-fb-feed-card'], 'Facebook predicts how likely you are to scroll past a post rather than engage with it.'), { ar: 'خطر التمرير دون توقف', en: 'Scroll-past risk' }, 'A weak first line.'),
  S('facebook.show_more_potential', 'facebook', 'attention', 'heuristic', rel('official', ['meta-fb-feed-card'], 'Facebook predicts clicking "Show more" when it is offered.'), { ar: 'النقر على «عرض المزيد»', en: '"Show more" potential' }, 'Only for long posts: the first lines must pull the reader in.'),
  S('facebook.click_potential', 'facebook', 'positive_engagement', 'heuristic', rel('official', ['meta-fb-feed-card'], 'Facebook predicts clicking a link and time spent on the website.'), { ar: 'قابلية النقر على الرابط', en: 'Link-click potential' }, 'Only for link posts.'),
  S('facebook.watch_retention', 'facebook', 'attention', 'heuristic', rel('official', ['meta-fb-feed-card'], 'Video watch-duration thresholds are listed signals.'), { ar: 'الاحتفاظ بالمشاهدة', en: 'Watch retention' }, 'Reels and video only: duration, rhythm, payoff.'),
  S('facebook.caption_readability', 'facebook', 'quality', 'derived', rel('research', ['osman-readability'], 'Readable captions.'), { ar: 'سهولة قراءة النص', en: 'Caption readability' }, 'Readability proxy.'),
  S('facebook.specificity', 'facebook', 'quality', 'derived', rel('heuristic', ['basira-heuristics'], 'Concrete claims.'), { ar: 'التحديد', en: 'Specificity' }, 'Numbers, units, few vague words.'),
  S('facebook.format_fit', 'facebook', 'format', 'derived', rel('heuristic', ['basira-heuristics'], 'Structure of the chosen format.'), { ar: 'ملاءمة الصيغة', en: 'Format fit' }, 'Post length, slide count or video duration within range.'),
  S('facebook.negative_feedback_risk', 'facebook', 'negative_feedback', 'heuristic', rel('heuristic', ['basira-heuristics'], 'Engagement bait and hostile wording invite hiding or reporting.'), { ar: 'خطر التفاعل السلبي', en: 'Negative-feedback risk' }, 'Engagement bait, hostile words, curiosity without substance.'),
  S('facebook.topic_affinity', 'facebook', 'historical', 'historical', rel('historical', ['account-history'], 'The account\'s results for this topic.'), { ar: 'ألفة الجمهور بالموضوع', en: 'Audience-topic affinity' }, 'This topic\'s median outcome against the account baseline.'),
  S('facebook.historical_performance', 'facebook', 'historical', 'historical', rel('historical', ['account-history'], 'Patterns that beat this account\'s baseline.'), { ar: 'أداء الحساب التاريخي', en: 'Historical performance' }, 'Matching account patterns.'),
];
