// Deterministic SYNTHETIC post histories for tests and the CLI demo. Not
// real account data: captions are realistic Arabic, metrics are drawn from
// a seeded generator with planted effects, so tests can check that the
// engine finds what was planted (and nothing it was not given).
//
// Planted on Instagram: numbered-list hooks get 1.4× shares per reach; one
// viral post has ~25× the median reach. Planted on X: short openings
// (≤ 8 words) get 1.5× replies per impression.

function rng(seed) {
  let s = seed >>> 0;
  return () => {
    s = (Math.imul(s, 1664525) + 1013904223) >>> 0;
    return s / 2 ** 32;
  };
}

const LIST_HOOKS = ['6 عادات تسرق تركيزك يوميًا', '5 أخطاء تجعلك أقل احترامًا دون أن تشعر', '7 كتب غيّرت طريقة تفكيري', '4 خطوات لتقرأ أكثر هذا الشهر', '3 أسئلة قبل أن تشتري أي كتاب', '8 علامات أنك تحتاج إلى استراحة', '6 أعداء تدمّر دماغك يوميًا', '5 عادات صباحية للقراء'];
const STATEMENT_HOOKS = ['القراءة اليومية تغيّر طريقة تفكيرك', 'كلما حاولت إرضاء الجميع، خسرت شيئًا من نفسك.', 'الكتاب الجيد لا ينتهي عند آخر صفحة', 'التركيز مهارة تُبنى ولا تُولد معك', 'المكتبة الصغيرة في بيتك تكفي لتبدأ'];
const QUESTION_HOOKS = ['لماذا تنسى ما تقرؤه بعد أسبوع؟', 'هل تقرأ لتتعلم أم لتنهي الكتاب؟', 'كم كتابًا قرأت هذا العام؟'];
const BODY = ['\nاحفظه لتعود إليه.', '\nأيّها يحدث معك أكثر؟ اكتب رقمه 👇', '\nشاركه مع صديق يحتاجه.', ''];

export function syntheticInstagram({ n = 48, seed = 7, listEffect = 1.4, viral = true, start = '2026-03-01T19:00:00+04:00' } = {}) {
  const r = rng(seed);
  const t0 = Date.parse(start);
  const posts = [];
  for (let i = 0; i < n; i++) {
    const kind = r();
    const list = kind < 0.45;
    const question = !list && kind < 0.6;
    const pool = list ? LIST_HOOKS : question ? QUESTION_HOOKS : STATEMENT_HOOKS;
    const hook = pool[Math.floor(r() * pool.length)];
    const type = r() < 0.6 ? 'CAROUSEL_ALBUM' : r() < 0.5 ? 'IMAGE' : 'VIDEO';
    const noise = () => 0.75 + 0.5 * r();
    let reach = Math.round(2400 * noise() * noise());
    if (viral && i === Math.floor(n / 2)) reach *= 25;
    const shares = Math.round((reach / 1000) * 8 * (list ? listEffect : 1) * noise());
    const saved = Math.round((reach / 1000) * 15 * noise());
    const comments = Math.round((reach / 1000) * 3 * noise());
    const likes = Math.round((reach / 1000) * 60 * noise());
    posts.push({
      id: `1790000000${String(i).padStart(4, '0')}`,
      caption: `${hook}${BODY[Math.floor(r() * BODY.length)]}`,
      media_type: type,
      media_product_type: type === 'VIDEO' ? 'REELS' : 'FEED',
      timestamp: new Date(t0 + i * 3 * 86400000).toISOString().replace('.000Z', '+0000'),
      permalink: `https://www.instagram.com/p/synthetic${i}/`,
      insights: {
        data: [
          { name: 'reach', values: [{ value: reach }] },
          { name: 'likes', values: [{ value: likes }] },
          { name: 'comments', values: [{ value: comments }] },
          { name: 'shares', values: [{ value: shares }] },
          { name: 'saved', values: [{ value: saved }] },
        ],
      },
    });
  }
  return { data: posts, note: 'SYNTHETIC data generated by tests/fixtures/algorithm/synthetic-history.js; not a real account.' };
}

export function syntheticX({ n = 40, seed = 11, shortEffect = 1.5, start = '2026-04-01T09:00:00Z' } = {}) {
  const r = rng(seed);
  const t0 = Date.parse(start);
  const SHORT = ['القراءة ليست هواية، إنها طريقة تفكير.', 'كتاب واحد في الشهر يكفي لتتغير.', 'لا تؤجّل ما تستطيع فعله اليوم', 'أفضل وقت للقراءة؟ الآن.'];
  const LONG = [
    'في كل مرة أفتح فيها كتابًا جديدًا أكتشف أن المشكلة لم تكن في الوقت بل في الطريقة التي أوزّع بها يومي بين الهاتف والعمل والراحة.',
    'تعلّمت بعد سنوات من القراءة أن أهم ما يبقى معك من أي كتاب ليس الاقتباسات الجميلة بل الأسئلة التي يتركها في رأسك لأيام.',
    'الكثيرون يظنون أن القراءة السريعة تعني فهمًا أقل، لكن التجربة تقول إن التركيز هو ما يصنع الفرق وليس سرعة العين على الصفحة.',
  ];
  const data = [];
  for (let i = 0; i < n; i++) {
    const short = r() < 0.5;
    const text = short ? SHORT[Math.floor(r() * SHORT.length)] : LONG[Math.floor(r() * LONG.length)];
    const noise = () => 0.75 + 0.5 * r();
    const impressions = Math.round(1800 * noise() * noise());
    const replies = Math.round((impressions / 1000) * 4 * (short ? shortEffect : 1) * noise());
    data.push({
      id: `18000000000000${String(i).padStart(5, '0')}`,
      text,
      created_at: new Date(t0 + i * 2 * 86400000).toISOString(),
      public_metrics: { retweet_count: Math.round((impressions / 1000) * 2 * noise()), reply_count: replies, like_count: Math.round((impressions / 1000) * 20 * noise()), quote_count: Math.round(r() * 3), bookmark_count: Math.round((impressions / 1000) * 3 * noise()), impression_count: impressions },
      non_public_metrics: { impression_count: impressions, user_profile_clicks: Math.round((impressions / 1000) * 5 * noise()), url_link_clicks: 0, engagements: Math.round((impressions / 1000) * 40 * noise()) },
    });
  }
  return { data, note: 'SYNTHETIC data generated by tests/fixtures/algorithm/synthetic-history.js; not a real account.' };
}
