// Builds the Claude plugin in claude-plugin/:
//   skills/arabic-carousel/assets/carousel.html   the full editor (classic + studio) as one offline file
//   skills/arabic-carousel/scripts/studio.mjs     the studio CLI (library, assets, memory, Canva plans)
//   skills/arabic-carousel/references/schema.json templates, compositions, fonts, palettes, plugins
//   skills/canva-arabic/scripts/canva.mjs         the canva_* tools as a CLI
//   skills/canva-arabic/scripts/canva-mcp.mjs     the same tools as a local MCP server (.mcp.json)
//   skills/canva-arabic/references/capabilities.md the capability table at build time
// and zips the plugin to dist/arabic-carousel-plugin.zip for upload.
// Run after changing templates, plugins, fonts or styles: npm run build:plugin
import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { build } from 'esbuild';
import postcss from 'postcss';
import tailwind from '@tailwindcss/postcss';
import JSZip from 'jszip';

const root = path.resolve(import.meta.dirname, '..');
const pluginDir = path.join(root, 'claude-plugin');
const skillDir = path.join(pluginDir, 'skills/arabic-carousel');
const canvaSkillDir = path.join(pluginDir, 'skills/canva-arabic');
const fontsource = path.join(root, 'node_modules/@fontsource');

const esbuildBase = { bundle: true, write: false, jsx: 'automatic', loader: { '.js': 'jsx' }, legalComments: 'none' };

async function bundleEditor() {
  const result = await build({
    ...esbuildBase,
    entryPoints: [path.join(root, 'scripts/standalone.jsx')],
    format: 'iife',
    minify: true,
    define: { 'process.env.NODE_ENV': '"production"' },
  });
  return result.outputFiles[0].text;
}

// A CLI as one ES module for Node 18+, no dependencies.
async function bundleCli(entry = 'scripts/studio-cli.js') {
  const result = await build({
    entryPoints: [path.join(root, entry)],
    bundle: true,
    write: false,
    platform: 'node',
    format: 'esm',
    target: 'node18',
    legalComments: 'none',
    banner: { js: '#!/usr/bin/env node\n// Generated by scripts/build-plugin.mjs from lib/studio — edit the sources, not this file.' },
  });
  return result.outputFiles[0].text;
}

async function compileCss() {
  const from = path.join(root, 'app/globals.css');
  const result = await postcss([tailwind({ base: root, optimize: true })]).process(await fs.readFile(from, 'utf8'), { from });
  return result.css;
}

// Same weights as app/layout.js. Only the arabic and latin subsets, woff2
// only, inlined as data URLs so the file works offline and the exporter has
// nothing to fetch.
const FONT_WEIGHTS = { cairo: [400, 700, 800], tajawal: [400, 500, 700, 800], almarai: [400, 700, 800], 'readex-pro': [400, 600, 700] };

async function inlineFonts() {
  const rules = [];
  for (const [family, weights] of Object.entries(FONT_WEIGHTS)) {
    for (const weight of weights) {
      for (const subset of ['arabic', 'latin']) {
        const css = await fs.readFile(path.join(fontsource, family, `${subset}-${weight}.css`), 'utf8');
        const file = css.match(/url\(\.\/files\/([^)]+\.woff2)\)/)[1];
        const data = (await fs.readFile(path.join(fontsource, family, 'files', file))).toString('base64');
        rules.push(css.replace(/src:[^;]+;/, `src: url(data:font/woff2;base64,${data}) format('woff2');`));
      }
    }
  }
  return rules.join('\n');
}

// Raw-text elements end at the first "</tag", so escape it inside them.
const escapeRawText = (text, tag) => text.replace(new RegExp(`</${tag}`, 'gi'), `<\\/${tag}`);

async function buildHtml() {
  const [js, css, fonts] = await Promise.all([bundleEditor(), compileCss(), inlineFonts()]);
  return `<!doctype html>
<html lang="ar" dir="rtl">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>كاروسيل عربي — بصيرة</title>
<style>${escapeRawText(fonts + css, 'style')}</style>
</head>
<body class="antialiased">
<div id="root"></div>
<script id="carousel-seed" type="application/json"></script>
<script>${escapeRawText(js, 'script')}</script>
</body>
</html>
`;
}

async function buildSchema() {
  const result = await build({ ...esbuildBase, entryPoints: [path.join(root, 'scripts/schema-entry.js')], format: 'esm', platform: 'node', packages: 'external' });
  const tmp = path.join(root, 'node_modules/.cache/carousel-schema.mjs');
  await fs.mkdir(path.dirname(tmp), { recursive: true });
  await fs.writeFile(tmp, result.outputFiles[0].text);
  const { templateList, overlayPlugins, PALETTES, FONTS, FORMATS, POLICY, compositionList, THEME_TOKENS, PATCH_ACTIONS, PREFERENCE_KEYS } = await import(pathToFileURL(tmp).href);
  await fs.rm(tmp);
  return {
    templates: templateList.map((t) => ({
      id: t.id,
      label: t.label,
      description: t.description,
      hideBrandBadge: Boolean(t.hideBrandBadge),
      fields: t.fields.map(({ key, label, type, hint }) => ({ key, label, type, ...(hint && { hint }) })),
    })),
    fonts: Object.entries(FONTS).map(([id, f]) => ({ id, label: f.label })),
    palettes: PALETTES.map(({ id, name, colors }) => ({ id, name, colors })),
    formats: Object.values(FORMATS).map(({ id, label, ratio, width, height }) => ({ id, label, ratio, width, height })),
    numerals: ['arab', 'latn'],
    institutional: { palettes: POLICY.palettes, font: POLICY.font, plugins: POLICY.plugins },
    plugins: overlayPlugins.map((p) => ({ id: p.id, label: p.label, defaults: p.defaults })),
    // Studio designs (schemaVersion 2): built with scripts/studio.mjs.
    studio: {
      compositions: compositionList.map((c) => ({
        id: c.id,
        label: c.label,
        type: c.type,
        description: c.description,
        variants: c.variants,
        capacity: c.capacity,
        tags: c.tags,
        fields: c.fields.map(({ key, label, type, required }) => ({ key, label, type, ...(required && { required }) })),
      })),
      themeTokens: THEME_TOKENS,
      patchActions: PATCH_ACTIONS,
      preferenceKeys: Object.fromEntries(Object.entries(PREFERENCE_KEYS).map(([k, v]) => [k, { label: v.label, ...(v.values && { values: v.values }) }])),
    },
  };
}

// The registry read against the schema snapshot in tests/fixtures plus the
// dated live evidence it carries. A snapshot only: the skill reruns
// canva_capabilities with the session's own tool schemas.
async function buildCapabilities() {
  const { CanvaCapabilityRegistry, registryMarkdown } = await import(pathToFileURL(path.join(root, 'lib/studio/canva/registry.js')).href);
  const fixture = JSON.parse(await fs.readFile(path.join(root, 'tests/fixtures/canva-schema-2026-10-02.json'), 'utf8'));
  const registry = new CanvaCapabilityRegistry();
  registry.loadSchemas(fixture, { at: fixture.capturedAt });
  const dated = registry.evidence.filter((e) => e.source === 'live').map((e) => `- ${e.at} — ${e.capability} (${e.route}): ${e.status}. ${e.note ?? ''}`);
  return `# قدرات Canva — لقطة وقت البناء

مولّد من \`lib/studio/canva/registry.js\` بمخططات أدوات Canva الملتقطة في ${fixture.capturedAt} ونتائج الاختبار الحي المؤرخة أدناه. **ليس مرجعًا ثابتًا**: أدوات الموصل تتغير، فشغّل \`canva_capabilities\` بمخططات جلستك قبل أي عمل؛ ما لم تُقرأ مخططاته في الجلسة يظهر «لم يُتحقق»، وأي اختبار حي على مخطط تغيّر بعده يصبح «قديمًا» ويُعاد التحقق منه.

الحالات: مدعوم · جزئي (يعمل بحدود مذكورة) · غير مدعوم · لم يُتحقق. المسارات: الموصل (ينفّذه المساعد) · ملف أصلي .pptx (يستورده المستخدم في Canva فيُنشئ تصميمًا جديدًا) · Connect API (برمز وصول من المستخدم) · يدوي في Canva.

${registryMarkdown(registry)}

## اختبارات حية مؤرخة

${dated.join('\n')}
`;
}

async function zipDir(dir, out, skip = []) {
  const zip = new JSZip();
  const walk = async (rel) => {
    for (const entry of await fs.readdir(path.join(dir, rel), { withFileTypes: true })) {
      const relPath = path.posix.join(rel, entry.name);
      if (skip.includes(relPath)) continue;
      if (entry.isDirectory()) await walk(relPath);
      else zip.file(relPath, await fs.readFile(path.join(dir, relPath)));
    }
  };
  await walk('');
  await fs.mkdir(path.dirname(out), { recursive: true });
  await fs.writeFile(out, await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' }));
}

const [html, schema, cli, canvaCli, canvaMcp, capabilities] = await Promise.all([
  buildHtml(),
  buildSchema(),
  bundleCli(),
  bundleCli('scripts/canva-cli.js'),
  bundleCli('scripts/canva-mcp.js'),
  buildCapabilities(),
]);
await fs.writeFile(path.join(skillDir, 'assets/carousel.html'), html);
await fs.writeFile(path.join(skillDir, 'scripts/studio.mjs'), cli, { mode: 0o755 });
await fs.writeFile(path.join(skillDir, 'references/schema.json'), `${JSON.stringify(schema, null, 2)}\n`);
await fs.mkdir(path.join(canvaSkillDir, 'scripts'), { recursive: true });
await fs.mkdir(path.join(canvaSkillDir, 'references'), { recursive: true });
await fs.writeFile(path.join(canvaSkillDir, 'scripts/canva.mjs'), canvaCli, { mode: 0o755 });
await fs.writeFile(path.join(canvaSkillDir, 'scripts/canva-mcp.mjs'), canvaMcp, { mode: 0o755 });
await fs.writeFile(path.join(canvaSkillDir, 'references/capabilities.md'), capabilities);
const zipPath = path.join(root, 'dist/arabic-carousel-plugin.zip');
await zipDir(pluginDir, zipPath);
// ChatGPT/Codex get only what OpenAI's packaging guide lists (plugin.json,
// assets/, skills/), without Claude's .claude-plugin/ folder or the local
// MCP server config (.mcp.json).
const chatgptZipPath = path.join(root, 'dist/arabic-carousel-chatgpt.zip');
await zipDir(pluginDir, chatgptZipPath, ['.claude-plugin', '.mcp.json']);

const kb = (n) => `${Math.round(n / 1024)} KB`;
console.log(`carousel.html  ${kb(Buffer.byteLength(html))}`);
console.log(`studio.mjs     ${kb(Buffer.byteLength(cli))}`);
console.log(`canva.mjs      ${kb(Buffer.byteLength(canvaCli))}, canva-mcp.mjs ${kb(Buffer.byteLength(canvaMcp))}`);
console.log(`plugin zip     ${kb((await fs.stat(zipPath)).size)} → ${path.relative(root, zipPath)} (Claude)`);
console.log(`plugin zip     ${kb((await fs.stat(chatgptZipPath)).size)} → ${path.relative(root, chatgptZipPath)} (ChatGPT, Codex)`);
